export const DEFAULT_DOCUMENT_NAME = "UNNAMED";
export const DEFAULT_PROJECT_NAME = "Project";

export const SET_RENAME_DOCUMENT_ACTION = "SET_RENAME_DOCUMENT_ACTION";
export const SET_RENAME_PROJECT_ACTION = "SET_RENAME_PROJECT_ACTION";
